name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: lucas-0liveira
          START_YEAR: 2023
          END_YEAR: 2023

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git pull --rebase origin main
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update 3D contribution profile for lucas-0liveira"
            git push origin main
          else
            echo "No changes to commit"
          fi
