name: GitHub-Profile-3D-Contrib

on:
  schedule: # Roda todos os dias às 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch: # Permite execução manual também

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: lucas-0liveira
 
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Update 3D profile"
          git push
